MvcKutuphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    [AllowAnonymous]
    public class KitapController : Controller
    {
        // GET: Kitap

        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();

        public ActionResult Index(string p)
        {
            //var degerler = db.TBL_KITAP.ToList();

            var degerler = from k in db.TBL_KITAP
                           select k;

            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(x => x.AD.Contains(p));
            }
            return View(degerler.ToList());
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1 = (from i in db.TBL_KATEGORI.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBL_YAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD + " " +  i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBL_KITAP p)
        {
            var ktg = db.TBL_KATEGORI.Where(k => k.ID == p.TBL_KATEGORI.ID).FirstOrDefault();
            var yzr = db.TBL_YAZAR.Where(y => y.ID == p.TBL_YAZAR.ID).FirstOrDefault();

            p.TBL_KATEGORI = ktg;
            p.TBL_YAZAR = yzr;

            db.TBL_KITAP.Add(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult KitapSil(int id)
        {
            var kitap = db.TBL_KITAP.Find(id);
            db.TBL_KITAP.Remove(kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBL_KITAP.Find(id);

            List<SelectListItem> deger1 = (from i in db.TBL_KATEGORI.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBL_YAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD + " " + i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View("KitapGetir", ktp);
        }
        public ActionResult KitapGuncelle(TBL_KITAP p)
        {
            //var ktg = db.TBL_KATEGORI.Find(p.ID);
            var kitap = db.TBL_KITAP.FirstOrDefault(k => k.ID == p.ID);
            kitap.AD = p.AD;
            kitap.BASIMYIL = p.BASIMYIL;
            kitap.YAYINEVI = p.YAYINEVI;
            kitap.SAYFA = p.SAYFA;
            kitap.DURUM = true;

            var ktg = db.TBL_KATEGORI.Where(k => k.ID == p.TBL_KATEGORI.ID).FirstOrDefault();
            var yzr = db.TBL_YAZAR.Where(y => y.ID == p.TBL_YAZAR.ID).FirstOrDefault();

            kitap.KATEGORI = ktg.ID;
            kitap.YAZAR = yzr.ID;

            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Kitap/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBL_KITAP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<link href="~/Css/TabloRenk.css" rel="stylesheet" />

<h2>Kitaplar</h2>

@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
{
    <div style="margin-bottom:15px; margin-top:15px; width:500px">
        <b>Aranacak Kitap Adını Giriniz..</b> @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </div>
}


<table class="table table-bordered">
    <tr class="tablorenk">
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kitap Yazarı</th>
        <th>Kategori</th>
        <th>Basım Yılı</th>
        <th>Yayınevi</th>
        <th>Sayfa</th>
        <th>Durum</th>
        <th>Silme</th>
        <th>Güncelleme</th>
    </tr>

    @foreach (var ktp in Model)
    {
        <tr>
            <td>@ktp.ID</td>
            <td>@ktp.AD</td>
            <td>@ktp.TBL_YAZAR.AD&nbsp @ktp.TBL_YAZAR.SOYAD</td>
            <td>@ktp.TBL_KATEGORI.AD</td>
            <td>@ktp.BASIMYIL</td>
            <td>@ktp.YAYINEVI</td>
            <td>@ktp.SAYFA</td>
            <td>@(ktp.DURUM == true ? "Aktif" : "Pasif")</td>
            <td>
                @Html.ActionLink("Sil", "KitapSil", new { id = ktp.ID }, new
                {
                    @class = "btn btn-danger",
                     onclick = "return confirm('Silmek İstediğinize Emin Misiniz ?')"
                })
            </td>
            <td><a href="/Kitap/KitapGetir/@ktp.ID" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>

<a href="/Kitap/KitapEkle/" class="btn btn-primary"> Yeni Kitap Ekle </a>

MvcKutuphane/Views/Kitap/KitapEkle.cshtml
@model MvcKutuphane.Models.Entity.TBL_KITAP

@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kitap Ekleme Sayfası</h2>

<br>

<form class="form-group" method="post">
    <div>
        <label>Kitap Adı : </label>
        @*<input type="text" class="form-control" name="AD" />*@
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control", @style = "width: 500px" })
    </div>
    <br>
    <div>
        <label>Kategori : </label>
        @Html.DropDownListFor(k => k.TBL_KATEGORI.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control", @style = "width : 500px" })
    </div>
    <br>
    <div>
        <label>Kitap Yazarı : </label>
        @Html.DropDownListFor(k => k.TBL_YAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control", @style = "width : 500px" })
    </div>
    <br>
    <div>
        <label>Basımyılı : </label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control", @style = "width: 500px" })
    </div>
    <br>
    <div>
        <label>Yayınevi : </label>
        @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control", @style = "width: 500px" })
    </div>
    <br>
    <div>
        <label>Sayfa : </label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control", @style = "width: 500px" })
    </div>
    <br>
    <input type="hidden" name="DURUM" value="True"/>
        @*@Html.HiddenFor(k => k.DURUM)*@
    <div>
        <button class="btn btn-info" id="Btn1">Ekle</button>
    </div>
</form>

MvcKutuphane/Views/Kitap/KitapGetir.cshtml
@model MvcKutuphane.Models.Entity.TBL_KITAP

@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kitap Güncelleme Sayfası</h2>

@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
    <div class="form-group">
        <label> Kitap Id : </label>
        @Html.TextBoxFor(y => y.ID, new { @class = "form-control", @style = "width : 500px" })
    </div>

    <div class="form-group" style="margin-top:22px">
        <label> Kitap Adı : </label>
        @Html.TextBoxFor(y => y.AD, new { @class = "form-control", @style = "width : 500px" })
    </div>

    <div class="form-group" style="margin-top:22px">
        <label> Kategori : </label>
        @Html.DropDownListFor(k => k.TBL_KATEGORI.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control", @style = "width : 500px" })
    </div>

    <div class="form-group" style="margin-top:22px">
        <label> Yazar Adı : </label>
        @Html.DropDownListFor(k => k.TBL_YAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control", @style = "width : 500px" })
    </div>

    <div class="form-group" style="margin-top:22px">
        <label> Basımyılı : </label>
        @Html.TextBoxFor(y => y.BASIMYIL, new { @class = "form-control", @style = "width : 500px" })
    </div>

    <div class="form-group" style="margin-top:22px">
        <label> Yayınevi : </label>
        @Html.TextBoxFor(y => y.YAYINEVI, new { @class = "form-control", @style = "width : 500px" })
    </div>

    <div class="form-group" style="margin-top:22px">
        <label> Sayfa : </label>
        @Html.TextBoxFor(y => y.SAYFA, new { @class = "form-control", @style = "width : 500px" })
    </div>

    //controllerdan default true getirttik, buraya gerek kalmadı
    @*<input type="hidden" name="DURUM" value="True" />*@

    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}