MvcKutuphane/Controllers/PersonelController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    [AllowAnonymous]
    public class PersonelController : Controller
    {
        // GET: Personel

        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();

        public ActionResult Index()
        {
            var degerler = db.TBL_PERSONEL.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(TBL_PERSONEL p)
        {
            if(!ModelState.IsValid)
            {
                return View("PersonelEkle");
            }

            db.TBL_PERSONEL.Add(p);
            db.SaveChanges();
            //  return View();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelSil(int id)
        {
            var personel = db.TBL_PERSONEL.Find(id);
            db.TBL_PERSONEL.Remove(personel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetir(int id)
        {
            var prs = db.TBL_PERSONEL.Find(id);
            return View("PersonelGetir", prs);
        }
        public ActionResult PersonelGuncelle(TBL_PERSONEL p)
        {
            //var ktg = db.TBL_KATEGORI.Find(p.ID);
            var prs = db.TBL_PERSONEL.FirstOrDefault(k => k.ID == p.ID);
            prs.PERSONEL = p.PERSONEL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Personel/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBL_PERSONEL>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<link href="~/Css/TabloRenk.css" rel="stylesheet" />

<h2>Personeller</h2>

<br>

<table class="table table-bordered">
    <tr class="tablorenk">
        <th>ID</th>
        <th>Personel Adı</th>
        <th>Silme</th>
        <th>Güncelleme</th>
    </tr>

    @foreach (var prs in Model)
    {
        <tr>
            <td>@prs.ID</td>
            <td>@prs.PERSONEL</td>
            <td><a href="/Personel/PersonelSil/@prs.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Personel/PersonelGetir/@prs.ID" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>

<a href="/Personel/PersonelEkle/" class="btn btn-primary"> Yeni Personel Ekle </a>

MvcKutuphane/Views/Personel/PersonelEkle.cshtml
@model MvcKutuphane.Models.Entity.TBL_PERSONEL

@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personel Ekleme Sayfası</h2>

<br>

<form class="form-group" method="post">
    <div>
        <label>Personel Adı : </label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x => x.PERSONEL, new {@class="form-control", @style = "width:500px" })
        @Html.ValidationMessageFor(x => x.PERSONEL, "", new {@style="color:red"})
    </div>
    <br>
    <div>
        <button class="btn btn-info" id="Btn1">Ekle</button>
    </div>
</form>

MvcKutuphane/Views/Personel/PersonelGetir.cshtml
@model MvcKutuphane.Models.Entity.TBL_PERSONEL

@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personel Güncelleme Sayfası</h2>

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
    <br>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.PERSONEL, "Personel Adı : ")
        @Html.TextBoxFor(k => k.PERSONEL, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}