MvcKutuphane/Controllers/UyeController.cs
using MvcKutuphane.Models.Entity;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    [AllowAnonymous]
    public class UyeController : Controller
    {
        // GET: Uye

        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();

        public ActionResult Index(int sayfa = 1)
        {
            //var degerler = db.TBL_UYELER.ToList();

            var degerler = db.TBL_UYELER.ToList().ToPagedList(sayfa, 3);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UyeEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UyeEkle(TBL_UYELER p)
        {
            if (!ModelState.IsValid)
            {
                return View("UyeEkle");
            }

            db.TBL_UYELER.Add(p);
            db.SaveChanges();
            //  return View();
            return RedirectToAction("Index");
        }
        public ActionResult UyeSil(int id)
        {
            var uyeler = db.TBL_UYELER.Find(id);
            db.TBL_UYELER.Remove(uyeler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UyeGetir(int id)
        {
            var prs = db.TBL_UYELER.Find(id);
            return View("UyeGetir", prs);
        }
        public ActionResult UyeGuncelle(TBL_UYELER p)
        {
            //var ktg = db.TBL_KATEGORI.Find(p.ID);
            var prs = db.TBL_UYELER.FirstOrDefault(k => k.ID == p.ID);
            prs.AD = p.AD;
            prs.SOYAD = p.SOYAD;
            prs.MAIL = p.MAIL;
            prs.KULLANICIADI = p.KULLANICIADI;
            prs.SIFRE = p.SIFRE;
            prs.FOTOGRAF = p.FOTOGRAF;
            prs.TELEFON = p.TELEFON;
            prs.OKUL = p.OKUL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UyeKitapGecmis(int id)
        {
            var ktpgecms = db.TBL_HAREKET.Where(x => x.UYE == id).ToList();

            var uyead = db.TBL_UYELER.Where(x => x.ID == id).Select(x => x.AD + " " + x.SOYAD).FirstOrDefault();

            ViewBag.dgr = uyead;

            return View(ktpgecms);
        }
    }
}

MvcKutuphane/Views/Uye/Index.cshtml
@using MvcKutuphane.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBL_UYELER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<link href="~/Css/TabloRenk.css" rel="stylesheet" />

<h2>Üyeler</h2>

<br>

<table class="table table-bordered">
    <tr class="tablorenk">
        <th>ID</th>
        <th>Üye Adı</th>
        <th>Üye Soyadı</th>
        <th>Mail</th>
        <th>Kullanıcı Adı</th>
        <th>Şifre</th>
        <th>Fotoğraf</th>
        <th>Telefon</th>
        <th>Okul</th>
        <th>Silme</th>
        <th>Güncelleme</th>
        <th>Kitap Geçmişi</th>
    </tr>

    @foreach (var uye in Model)
    {
        <tr>
            <td>@uye.ID</td>
            <td>@uye.AD</td>
            <td>@uye.SOYAD</td>
            <td>@uye.MAIL</td>
            <td>@uye.KULLANICIADI</td>
            <td>@uye.SIFRE</td>
            <td>@uye.FOTOGRAF</td>
            <td>@uye.TELEFON</td>
            <td>@uye.OKUL</td>
            <td><a href="/Uye/UyeSil/@uye.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Uye/UyeGetir/@uye.ID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Uye/UyeKitapGecmis/@uye.ID" class="btn btn-info">Kitap Geçmişi</a></td>
        </tr>
    }
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<a href="/Uye/UyeEkle/" class="btn btn-primary"> Yeni Üye Ekle </a>

MvcKutuphane/Views/Uye/UyeEkle.cshtml
@model MvcKutuphane.Models.Entity.TBL_UYELER

@{
    ViewBag.Title = "UyeEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üye Ekleme Sayfası</h2>

<br>

<form class="form-group" method="post">
    <div>
        <label>Üye Adı : </label>
        @Html.TextBoxFor(x => x.AD, new { @class = "form-control", @style = "width:500px" })
        @Html.ValidationMessageFor(x => x.AD, "", new { @style = "color:red" })
    </div>
    <br>

    <div>
        <label>Üye Soyadı : </label>
        @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control", @style = "width:500px" })
    </div>
    <br>

    <div>
        <label>Mail : </label>
        @Html.TextBoxFor(x => x.MAIL, new { @class = "form-control", @style = "width:500px" })
    </div>
    <br>

    <div>
        <label>Kullanıcı Adı : </label>
        @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control", @style = "width:500px" })
    </div>
    <br>

    <div>
        <label>Şifre : </label>
        @Html.TextBoxFor(x => x.SIFRE, new { @class = "form-control", @style = "width:500px" })
        @Html.ValidationMessageFor(x => x.SIFRE, "", new { @style = "color:red" })
    </div>
    <br>

    <div>
        <label>Fotoğraf : </label>
        @Html.TextBoxFor(x => x.FOTOGRAF, new { @class = "form-control", @style = "width:500px" })
    </div>
    <br>

    <div>
        <label>Telefon : </label>
        @Html.TextBoxFor(x => x.TELEFON, new { @class = "form-control", @style = "width:500px" })
    </div>
    <br>

    <div>
        <label>Okul : </label>
        @Html.TextBoxFor(x => x.OKUL, new { @class = "form-control", @style = "width:500px" })
    </div>
    <br>
    <div>
        <button class="btn btn-info" id="Btn1">Ekle</button>
    </div>
</form>

MvcKutuphane/Views/Uye/UyeGetir.cshtml
@model MvcKutuphane.Models.Entity.TBL_UYELER

@{
    ViewBag.Title = "UyeGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üye Güncelleme Sayfası</h2>

@using (Html.BeginForm("UyeGuncelle", "Uye", FormMethod.Post))
{
    <br>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.AD, "Üye Adı : ")
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.SOYAD, "Üye Soyadı : ")
        @Html.TextBoxFor(k => k.SOYAD, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.MAIL, "Mail : ")
        @Html.TextBoxFor(k => k.MAIL, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.KULLANICIADI, "Kullanıcı Adı : ")
        @Html.TextBoxFor(k => k.KULLANICIADI, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.SIFRE, "Şifre : ")
        @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.FOTOGRAF, "Fotoğraf : ")
        @Html.TextBoxFor(k => k.FOTOGRAF, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.TELEFON, "Telefon : ")
        @Html.TextBoxFor(k => k.TELEFON, new { @class = "form-control", @style = "width: 500px" })
    </div>

    <div class="form-group">
        @Html.LabelFor(k => k.OKUL, "Okul : ")
        @Html.TextBoxFor(k => k.OKUL, new { @class = "form-control", @style = "width: 500px" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Uye/UyeKitapGecmis.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBL_HAREKET>

@{
    ViewBag.Title = "UyeKitapGecmis";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üye : @ViewBag.dgr</h2>

<br>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>Üyenin Getirdiği Tarih</th>
    </tr>

    @foreach (var uye in Model)
    {
        <tr>
            <td>@uye.ID</td>
            <td>@uye.TBL_KITAP.AD</td>
            <td>@uye.TBL_PERSONEL.PERSONEL</td>
            <td>@Convert.ToDateTime(uye.ALISTARIH).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(uye.IADETARIH).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(uye.UYEGETIRTARIH).ToString("dd/MM/yyyy")</td>
        </tr>
    }
</table>